
!$COLOR_INDEX_0="#9E0142"
!$COLOR_INDEX_1="#D53E4F"
!$COLOR_INDEX_2="#F46D43"
!$COLOR_INDEX_3="#FDAE61"
!$COLOR_INDEX_4="#FEE08B"
!$COLOR_INDEX_5="#FFFFBF"
!$COLOR_INDEX_6="#E6F598"
!$COLOR_INDEX_7="#ABDDA4"
!$COLOR_INDEX_8="#66C2A5"
!$COLOR_INDEX_9="#3288BD"
!$COLOR_INDEX_10="#5E4FA2"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#D53E4F"
!$COLOR_TEXT_NEUTRAL="#FFFFBF"
!$COLOR_TEXT_DARK="#3288BD"

!$COLOR_REL_COLOR="#5E4FA2"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
