
!$COLOR_INDEX_0="#A50026"
!$COLOR_INDEX_1="#D73027"
!$COLOR_INDEX_2="#F46D43"
!$COLOR_INDEX_3="#FDAE61"
!$COLOR_INDEX_4="#FEE08B"
!$COLOR_INDEX_5="#FFFFBF"
!$COLOR_INDEX_6="#D9EF8B"
!$COLOR_INDEX_7="#A6D96A"
!$COLOR_INDEX_8="#66BD63"
!$COLOR_INDEX_9="#1A9850"
!$COLOR_INDEX_10="#006837"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#D73027"
!$COLOR_TEXT_NEUTRAL="#FFFFBF"
!$COLOR_TEXT_DARK="#1A9850"

!$COLOR_REL_COLOR="#006837"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
