
!$COLOR_INDEX_0="#67001F"
!$COLOR_INDEX_1="#B2182B"
!$COLOR_INDEX_2="#D6604D"
!$COLOR_INDEX_3="#F4A582"
!$COLOR_INDEX_4="#FDDBC7"
!$COLOR_INDEX_5="#FFFFFF"
!$COLOR_INDEX_6="#E0E0E0"
!$COLOR_INDEX_7="#BABABA"
!$COLOR_INDEX_8="#878787"
!$COLOR_INDEX_9="#4D4D4D"
!$COLOR_INDEX_10="#1A1A1A"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#B2182B"
!$COLOR_TEXT_NEUTRAL="#FFFFFF"
!$COLOR_TEXT_DARK="#4D4D4D"

!$COLOR_REL_COLOR="#1A1A1A"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
