
!$COLOR_INDEX_0="#543005"
!$COLOR_INDEX_1="#8C510A"
!$COLOR_INDEX_2="#BF812D"
!$COLOR_INDEX_3="#DFC27D"
!$COLOR_INDEX_4="#F6E8C3"
!$COLOR_INDEX_5="#F5F5F5"
!$COLOR_INDEX_6="#C7EAE5"
!$COLOR_INDEX_7="#80CDC1"
!$COLOR_INDEX_8="#35978F"
!$COLOR_INDEX_9="#01665E"
!$COLOR_INDEX_10="#003C30"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#8C510A"
!$COLOR_TEXT_NEUTRAL="#F5F5F5"
!$COLOR_TEXT_DARK="#01665E"

!$COLOR_REL_COLOR="#003C30"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
