
!$COLOR_INDEX_0="#B2182B"
!$COLOR_INDEX_1="#D6604D"
!$COLOR_INDEX_2="#F4A582"
!$COLOR_INDEX_3="#FDDBC7"
!$COLOR_INDEX_4="#F7F7F7"
!$COLOR_INDEX_5="#D1E5F0"
!$COLOR_INDEX_6="#92C5DE"
!$COLOR_INDEX_7="#4393C3"
!$COLOR_INDEX_8="#2166AC"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#D6604D"
!$COLOR_TEXT_NEUTRAL="#F7F7F7"
!$COLOR_TEXT_DARK="#2166AC"

!$COLOR_REL_COLOR="#2166AC"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
