
!$COLOR_INDEX_0="#D73027"
!$COLOR_INDEX_1="#F46D43"
!$COLOR_INDEX_2="#FDAE61"
!$COLOR_INDEX_3="#FEE090"
!$COLOR_INDEX_4="#FFFFBF"
!$COLOR_INDEX_5="#E0F3F8"
!$COLOR_INDEX_6="#ABD9E9"
!$COLOR_INDEX_7="#74ADD1"
!$COLOR_INDEX_8="#4575B4"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#F46D43"
!$COLOR_TEXT_NEUTRAL="#FFFFBF"
!$COLOR_TEXT_DARK="#4575B4"

!$COLOR_REL_COLOR="#4575B4"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
