
!$COLOR_INDEX_0="#D73027"
!$COLOR_INDEX_1="#F46D43"
!$COLOR_INDEX_2="#FDAE61"
!$COLOR_INDEX_3="#FEE08B"
!$COLOR_INDEX_4="#FFFFBF"
!$COLOR_INDEX_5="#D9EF8B"
!$COLOR_INDEX_6="#A6D96A"
!$COLOR_INDEX_7="#66BD63"
!$COLOR_INDEX_8="#1A9850"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#F46D43"
!$COLOR_TEXT_NEUTRAL="#FFFFBF"
!$COLOR_TEXT_DARK="#1A9850"

!$COLOR_REL_COLOR="#1A9850"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
