
!$COLOR_INDEX_0="#8DD3C7"
!$COLOR_INDEX_1="#FFFFB3"
!$COLOR_INDEX_2="#BEBADA"
!$COLOR_INDEX_3="#FB8072"
!$COLOR_INDEX_4="#80B1D3"
!$COLOR_INDEX_5="#FDB462"
!$COLOR_INDEX_6="#B3DE69"
!$COLOR_INDEX_7="#FCCDE5"
!$COLOR_INDEX_8="#D9D9D9"
!$COLOR_INDEX_9="#BC80BD"
!$COLOR_INDEX_10="#CCEBC5"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FFFFB3"
!$COLOR_TEXT_NEUTRAL="#FDB462"
!$COLOR_TEXT_DARK="#BC80BD"

!$COLOR_REL_COLOR="#CCEBC5"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
