
!$COLOR_INDEX_0="#FBB4AE"
!$COLOR_INDEX_1="#B3CDE3"
!$COLOR_INDEX_2="#CCEBC5"
!$COLOR_INDEX_3="#DECBE4"
!$COLOR_INDEX_4="#FED9A6"
!$COLOR_INDEX_5="#FFFFCC"
!$COLOR_INDEX_6="#E5D8BD"
!$COLOR_INDEX_7="#FDDAEC"
!$COLOR_INDEX_8="#F2F2F2"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#B3CDE3"
!$COLOR_TEXT_NEUTRAL="#FED9A6"
!$COLOR_TEXT_DARK="#F2F2F2"

!$COLOR_REL_COLOR="#F2F2F2"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
