
!$COLOR_INDEX_0="#A6CEE3"
!$COLOR_INDEX_1="#1F78B4"
!$COLOR_INDEX_2="#B2DF8A"
!$COLOR_INDEX_3="#33A02C"
!$COLOR_INDEX_4="#FB9A99"
!$COLOR_INDEX_5="#E31A1C"
!$COLOR_INDEX_6="#FDBF6F"
!$COLOR_INDEX_7="#FF7F00"
!$COLOR_INDEX_8="#CAB2D6"
!$COLOR_INDEX_9="#6A3D9A"
!$COLOR_INDEX_10="#FFFF99"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#1F78B4"
!$COLOR_TEXT_NEUTRAL="#E31A1C"
!$COLOR_TEXT_DARK="#6A3D9A"

!$COLOR_REL_COLOR="#FFFF99"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
