
!$COLOR_INDEX_0="#F7FCF5"
!$COLOR_INDEX_1="#E5F5E0"
!$COLOR_INDEX_2="#C7E9C0"
!$COLOR_INDEX_3="#A1D99B"
!$COLOR_INDEX_4="#74C476"
!$COLOR_INDEX_5="#41AB5D"
!$COLOR_INDEX_6="#238B45"
!$COLOR_INDEX_7="#006D2C"
!$COLOR_INDEX_8="#00441B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E5F5E0"
!$COLOR_TEXT_NEUTRAL="#74C476"
!$COLOR_TEXT_DARK="#00441B"

!$COLOR_REL_COLOR="#00441B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
