
!$COLOR_INDEX_0="#FFFFD9"
!$COLOR_INDEX_1="#EDF8B1"
!$COLOR_INDEX_2="#C7E9B4"
!$COLOR_INDEX_3="#7FCDBB"
!$COLOR_INDEX_4="#41B6C4"
!$COLOR_INDEX_5="#1D91C0"
!$COLOR_INDEX_6="#225EA8"
!$COLOR_INDEX_7="#253494"
!$COLOR_INDEX_8="#081D58"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#EDF8B1"
!$COLOR_TEXT_NEUTRAL="#41B6C4"
!$COLOR_TEXT_DARK="#081D58"

!$COLOR_REL_COLOR="#081D58"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
