
!$COLOR_INDEX_0="#FFF7FB"
!$COLOR_INDEX_1="#ECE2F0"
!$COLOR_INDEX_2="#D0D1E6"
!$COLOR_INDEX_3="#A6BDDB"
!$COLOR_INDEX_4="#67A9CF"
!$COLOR_INDEX_5="#3690C0"
!$COLOR_INDEX_6="#02818A"
!$COLOR_INDEX_7="#016C59"
!$COLOR_INDEX_8="#014636"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#ECE2F0"
!$COLOR_TEXT_NEUTRAL="#67A9CF"
!$COLOR_TEXT_DARK="#014636"

!$COLOR_REL_COLOR="#014636"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
