
!$COLOR_INDEX_0="#F7FCFD"
!$COLOR_INDEX_1="#E0ECF4"
!$COLOR_INDEX_2="#BFD3E6"
!$COLOR_INDEX_3="#9EBCDA"
!$COLOR_INDEX_4="#8C96C6"
!$COLOR_INDEX_5="#8C6BB1"
!$COLOR_INDEX_6="#88419D"
!$COLOR_INDEX_7="#810F7C"
!$COLOR_INDEX_8="#4D004B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E0ECF4"
!$COLOR_TEXT_NEUTRAL="#8C96C6"
!$COLOR_TEXT_DARK="#4D004B"

!$COLOR_REL_COLOR="#4D004B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
