
!$COLOR_INDEX_0="#F7FCFD"
!$COLOR_INDEX_1="#E5F5F9"
!$COLOR_INDEX_2="#CCECE6"
!$COLOR_INDEX_3="#99D8C9"
!$COLOR_INDEX_4="#66C2A4"
!$COLOR_INDEX_5="#41AE76"
!$COLOR_INDEX_6="#238B45"
!$COLOR_INDEX_7="#006D2C"
!$COLOR_INDEX_8="#00441B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E5F5F9"
!$COLOR_TEXT_NEUTRAL="#66C2A4"
!$COLOR_TEXT_DARK="#00441B"

!$COLOR_REL_COLOR="#00441B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
