# We don't include a [deploy] config block because
# it's built and deployed by netlify
baseurl: ""
theme: "hugo-theme-stack"
# Documentation: https://github.com/adityatelange/hugo-PaperMod/wiki
title: Matt Weagle
paginate: 7

outputs:
  home:
    - HTML
    - RSS

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

module:
  hugoVersion:
    extended: true
    min: "0.87.0"

params:
  mainSections:
    - posts
    - twitter
  featuredImageField: image
  rssFullContent: true
  favicon:

  footer:
    since:
    customText:

  dateFormat:
    published: 2006-01-02
    lastUpdated: 2006-01-02T15:04:05Z

  sidebar:
    compact: false
    emoji:
    subtitle: People, Ideas, Technology
    avatar:
      enabled: true
      local: true
      #src: img/mweagle.jpg
      src: home-icon-silhouette-svgrepo-com.png

  article:
    math: false
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false

  widgets:
    homepage:
      - type: search
      - type: tag-cloud
        params:
          limit: 10
      - type: categories
        params:
          limit: 10

  opengraph:
    twitter:
      # Your Twitter username
      site:

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

  social:
    - identifier: linkedin
      name: Linked In
      url: https://www.linkedin.com/in/mweagle/
      params:
        icon: brand-linkedin
    - identifier: github
      name: GitHub
      url: https://github.com/mweagle
      params:
        icon: brand-github
    - identifier: mastodon
      name: Mastodon
      url: https://hachyderm.io/@mweagle
      params:
        icon: brand-mastodon

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
