// +build mage

// lint:file-ignore U1000 Ignore all  code, it's only for development

package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/magefile/mage/mg" // mg contains helpful utility functions, like Deps
	"github.com/magefile/mage/sh" // mg contains helpful utility functions, like Deps
	archiver "github.com/mholt/archiver/v3"
	"github.com/pkg/browser"
)

const (
	localWorkDir = "./.vscode"
	hugoVersion  = "0.62.0"
)

func xplatPath(pathParts ...string) string {
	return filepath.Join(pathParts...)
}

var (
	hugoPath = filepath.Join(localWorkDir, "hugo")
	header   = strings.Repeat("-", 80)
)

// mageLog is a mage verbose aware log function
func mageLog(formatSpecifier string, args ...interface{}) {
	if mg.Verbose() {
		if len(args) != 0 {
			log.Printf(formatSpecifier, args...)
		} else {
			log.Print(formatSpecifier)
		}
	}
}

// runScript is a 2d array of commands to run as a script
func runScript(commands [][]string) error {
	for _, eachCommand := range commands {
		var commandErr error
		if len(eachCommand) <= 1 {
			commandErr = sh.Run(eachCommand[0])
		} else {
			commandErr = sh.Run(eachCommand[0], eachCommand[1:]...)
		}
		if commandErr != nil {
			return commandErr
		}
	}
	return nil
}

func gitCommit(shortVersion bool) (string, error) {
	args := []string{
		"rev-parse",
	}
	if shortVersion {
		args = append(args, "--short")
	}
	args = append(args, "HEAD")
	val, valErr := sh.Output("git", args...)
	return strings.TrimSpace(val), valErr
}

// EnsureCleanTree ensures that the git tree is clean
func EnsureCleanTree() error {
	cleanTreeScript := [][]string{
		// No dirty trees
		{"git", "diff", "--exit-code"},
	}
	return runScript(cleanTreeScript)
}

////////////////////////////////////////////////////////////////////////////////
// START - DOCUMENTATION
////////////////////////////////////////////////////////////////////////////////

// ensureWorkDir ensures that the scratch directory exists
func ensureWorkDir() error {
	return os.MkdirAll(localWorkDir, os.ModePerm)
}

func runHugoCommand(hugoCommandArgs ...string) error {
	absHugoPath, absHugoPathErr := filepath.Abs(hugoPath)
	if absHugoPathErr != nil {
		return absHugoPathErr
	}

	// Get the git short value
	gitSHA, gitSHAErr := gitCommit(true)
	if gitSHAErr != nil {
		return gitSHAErr
	}

	var output io.Writer
	if mg.Verbose() {
		output = os.Stdout
	}
	cmd := exec.Command(absHugoPath, hugoCommandArgs...)
	cmd.Env = append(os.Environ(), fmt.Sprintf("GIT_HEAD_COMMIT=%s", gitSHA))
	cmd.Stderr = os.Stderr
	cmd.Stdout = output
	return cmd.Run()
}

// DocsInstallRequirements installs the required Hugo version
func DocsInstallRequirements() error {
	mg.SerialDeps(ensureWorkDir)

	// Is hugo already installed?
	mageLog("Checking for Hugo version: %s", hugoVersion)

	hugoOutput, hugoOutputErr := sh.Output(hugoPath, "version")
	if hugoOutputErr == nil && strings.Contains(hugoOutput, hugoVersion) {
		mageLog("Hugo version %s already installed at %s", hugoVersion, hugoPath)
		return nil
	}

	hugoArchiveName := ""
	switch runtime.GOOS {
	case "darwin":
		hugoArchiveName = "macOS-64bit.tar.gz"
	case "linux":
		hugoArchiveName = "Linux-64bit.tar.gz"
	default:
		hugoArchiveName = fmt.Sprintf("UNSUPPORTED_%s", runtime.GOOS)
	}

	hugoURL := fmt.Sprintf("https://github.com/gohugoio/hugo/releases/download/v%s/hugo_extended_%s_%s",
		hugoVersion,
		hugoVersion,
		hugoArchiveName)

	mageLog("Installing Hugo from source: %s", hugoURL)
	outputArchive := filepath.Join(localWorkDir, "hugo.tar.gz")
	outputFile, outputErr := os.Create(outputArchive)
	if outputErr != nil {
		return outputErr
	}

	hugoResp, hugoRespErr := http.Get(hugoURL)
	if hugoRespErr != nil {
		return hugoRespErr
	}
	defer hugoResp.Body.Close()

	_, copyBytesErr := io.Copy(outputFile, hugoResp.Body)
	if copyBytesErr != nil {
		return copyBytesErr
	}
	// Great, go heads and untar it...
	unarchiver := archiver.NewTarGz()
	unarchiver.OverwriteExisting = true
	untarErr := unarchiver.Unarchive(outputArchive, localWorkDir)
	if untarErr != nil {
		return untarErr
	}
	versionScript := [][]string{
		{hugoPath, "version"},
	}
	return runScript(versionScript)
}

// DocsBuild builds the public documentation site in the /docs folder
func DocsBuild() error {
	cleanDocsDirectory := func() error {
		docsDir, docsDirErr := filepath.Abs("public")
		if docsDirErr != nil {
			return docsDirErr
		}
		mageLog("Cleaning output directory: %s", docsDir)
		return os.RemoveAll(docsDir)
	}

	mg.SerialDeps(DocsInstallRequirements,
		cleanDocsDirectory)
	return runHugoCommand()
}

// // DocsCommit builds and commits the current
// // documentation with an autogenerated comment
// func DocsCommit() error {
// 	mg.SerialDeps(DocsBuild)

// 	commitNoMessageScript := make([][]string, 0)
// 	for _, eachPath := range hugoDocsPaths {
// 		commitNoMessageScript = append(commitNoMessageScript,
// 			[]string{"git", "add", "--all", eachPath},
// 		)
// 	}
// 	commitNoMessageScript = append(commitNoMessageScript,
// 		[]string{"git", "commit", "-m", `"Documentation updates"`},
// 	)
// 	return runScript(commitNoMessageScript)
// }

// DocsEdit starts a Hugo server and hot reloads the documentation at http://localhost:1313
func DocsEdit() error {
	mg.SerialDeps(DocsInstallRequirements)

	editCommandArgs := []string{
		"server",
		"--disableFastRender",
		"--watch",
		"--forceSyncStatic",
		"--verbose",
	}
	go func() {
		mageLog("Waiting for docs to build...")
		time.Sleep(3 * time.Second)
		browser.OpenURL("http://localhost:1313")
	}()
	return runHugoCommand(editCommandArgs...)
}

////////////////////////////////////////////////////////////////////////////////
// END - DOCUMENTATION
////////////////////////////////////////////////////////////////////////////////
