!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4.puml
!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4_Component.puml
!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4_Container.puml
!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4_Context.puml
!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4_Deployment.puml
!include https://mweagle.io/resources/C4-PlantUML-2.5.0/C4_Dynamic.puml


' Globals/Users/mweagle/Library/CloudStorage/Dropbox/Apps/Github/blog/static/resources/C4-PlantUML-2.5.0
skinparam DefaultFontName Avenir
skinparam Handwritten false
skinparam TitleFontSize 32

'skinparam linetype ortho
skinparam WrapWidth 200
skinparam MaxMessageSize 200