!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4.puml)
!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4_Component.puml)
!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4_Container.puml)
!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4_Context.puml)
!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4_Deployment.puml)
!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/C4-PlantUML/C4_Dynamic.puml)

' Globals/Users/mweagle/Library/CloudStorage/Dropbox/Apps/Github/blog/static/resources/C4-PlantUML
skinparam DefaultFontName Avenir
skinparam Handwritten false
skinparam TitleFontSize 32

'skinparam linetype ortho
skinparam WrapWidth 200
skinparam MaxMessageSize 200