' Include the common theme elements

!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/c4-theme-common.puml)
'!include ./c4-theme-common.puml

!define PUMLNAME(a,b,c) ##a-##b-##c.puml

' Styling information for C4
' https://github.com/plantuml-stdlib/C4-PlantUML/issues/245
!$PALETTE_THEME_NAME?=PUMLNAME($PALETTE_TYPE, $PALETTE_NAME, $PALETTE_COLOR_COUNT)

!include INCLUDE($ROOT_PATH, c4pumlthemes/puml/resources/colorbrewer/palettes/$PALETTE_THEME_NAME)


' Internal
!if ($PALETTE_COLOR_COUNT == 9)
  ' Internal
  UpdateElementStyle("person", $bgColor=$COLOR_INDEX_7, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $sprite="person2")
  UpdateElementStyle("system", $bgColor=$COLOR_INDEX_5, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR)
  UpdateElementStyle("container", $bgColor=$COLOR_INDEX_3, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR)
  UpdateElementStyle("component", $bgColor=$COLOR_INDEX_1, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR)
  '' External
  UpdateElementStyle("external_person", $bgColor=$COLOR_INDEX_6, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $sprite="person2", $shadowing="true")
  UpdateElementStyle("external_system", $bgColor=$COLOR_INDEX_4, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
  UpdateElementStyle("external_container", $bgColor=$COLOR_INDEX_2, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
  UpdateElementStyle("external_component", $bgColor=$COLOR_INDEX_0, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
!elseif ($PALETTE_COLOR_COUNT == 11)
  UpdateElementStyle("person", $bgColor=$COLOR_INDEX_9, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $sprite="person2")
  UpdateElementStyle("system", $bgColor=$COLOR_INDEX_7, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR)
  UpdateElementStyle("container", $bgColor=$COLOR_INDEX_4, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR)
  UpdateElementStyle("component", $bgColor=$COLOR_INDEX_1, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR)
  '' External
  UpdateElementStyle("external_person", $bgColor=$COLOR_INDEX_7, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $sprite="person2", $shadowing="true")
  UpdateElementStyle("external_system", $bgColor=$COLOR_INDEX_6, $fontColor=$COLOR_TEXT_LIGHT, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
  UpdateElementStyle("external_container", $bgColor=$COLOR_INDEX_3, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
  UpdateElementStyle("external_component", $bgColor=$COLOR_INDEX_0, $fontColor=$COLOR_TEXT_DARK, $borderColor=$COLOR_BORDER_COLOR, $shadowing="true")
  UpdateRelStyle($lineColor=$COLOR_REL_COLOR, $textColor=$COLOR_REL_COLOR)
$else
  !log Unsupported PALETTE_COLOR_COUNT value: $PALETTE_COLOR_COUNT
!endif

' Common C4 settings
UpdateRelStyle($lineColor=$COLOR_REL_COLOR, $textColor=$COLOR_REL_COLOR)

