
!$COLOR_INDEX_0="#C51B7D"
!$COLOR_INDEX_1="#DE77AE"
!$COLOR_INDEX_2="#F1B6DA"
!$COLOR_INDEX_3="#FDE0EF"
!$COLOR_INDEX_4="#F7F7F7"
!$COLOR_INDEX_5="#E6F5D0"
!$COLOR_INDEX_6="#B8E186"
!$COLOR_INDEX_7="#7FBC41"
!$COLOR_INDEX_8="#4D9221"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#DE77AE"
!$COLOR_TEXT_NEUTRAL="#F7F7F7"
!$COLOR_TEXT_DARK="#4D9221"

!$COLOR_REL_COLOR="#4D9221"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
