
!$COLOR_INDEX_0="#40004B"
!$COLOR_INDEX_1="#762A83"
!$COLOR_INDEX_2="#9970AB"
!$COLOR_INDEX_3="#C2A5CF"
!$COLOR_INDEX_4="#E7D4E8"
!$COLOR_INDEX_5="#F7F7F7"
!$COLOR_INDEX_6="#D9F0D3"
!$COLOR_INDEX_7="#A6DBA0"
!$COLOR_INDEX_8="#5AAE61"
!$COLOR_INDEX_9="#1B7837"
!$COLOR_INDEX_10="#00441B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#762A83"
!$COLOR_TEXT_NEUTRAL="#F7F7F7"
!$COLOR_TEXT_DARK="#1B7837"

!$COLOR_REL_COLOR="#00441B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
