
!$COLOR_INDEX_0="#7F3B08"
!$COLOR_INDEX_1="#B35806"
!$COLOR_INDEX_2="#E08214"
!$COLOR_INDEX_3="#FDB863"
!$COLOR_INDEX_4="#FEE0B6"
!$COLOR_INDEX_5="#F7F7F7"
!$COLOR_INDEX_6="#D8DAEB"
!$COLOR_INDEX_7="#B2ABD2"
!$COLOR_INDEX_8="#8073AC"
!$COLOR_INDEX_9="#542788"
!$COLOR_INDEX_10="#2D004B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#B35806"
!$COLOR_TEXT_NEUTRAL="#F7F7F7"
!$COLOR_TEXT_DARK="#542788"

!$COLOR_REL_COLOR="#2D004B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
