
!$COLOR_INDEX_0="#D53E4F"
!$COLOR_INDEX_1="#F46D43"
!$COLOR_INDEX_2="#FDAE61"
!$COLOR_INDEX_3="#FEE08B"
!$COLOR_INDEX_4="#FFFFBF"
!$COLOR_INDEX_5="#E6F598"
!$COLOR_INDEX_6="#ABDDA4"
!$COLOR_INDEX_7="#66C2A5"
!$COLOR_INDEX_8="#3288BD"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#F46D43"
!$COLOR_TEXT_NEUTRAL="#FFFFBF"
!$COLOR_TEXT_DARK="#3288BD"

!$COLOR_REL_COLOR="#3288BD"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
