
!$COLOR_INDEX_0="#B35806"
!$COLOR_INDEX_1="#E08214"
!$COLOR_INDEX_2="#FDB863"
!$COLOR_INDEX_3="#FEE0B6"
!$COLOR_INDEX_4="#F7F7F7"
!$COLOR_INDEX_5="#D8DAEB"
!$COLOR_INDEX_6="#B2ABD2"
!$COLOR_INDEX_7="#8073AC"
!$COLOR_INDEX_8="#542788"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E08214"
!$COLOR_TEXT_NEUTRAL="#F7F7F7"
!$COLOR_TEXT_DARK="#542788"

!$COLOR_REL_COLOR="#542788"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
