
!$COLOR_INDEX_0="#B2182B"
!$COLOR_INDEX_1="#D6604D"
!$COLOR_INDEX_2="#F4A582"
!$COLOR_INDEX_3="#FDDBC7"
!$COLOR_INDEX_4="#FFFFFF"
!$COLOR_INDEX_5="#E0E0E0"
!$COLOR_INDEX_6="#BABABA"
!$COLOR_INDEX_7="#878787"
!$COLOR_INDEX_8="#4D4D4D"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#D6604D"
!$COLOR_TEXT_NEUTRAL="#FFFFFF"
!$COLOR_TEXT_DARK="#4D4D4D"

!$COLOR_REL_COLOR="#4D4D4D"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
