
!$COLOR_INDEX_0="#E41A1C"
!$COLOR_INDEX_1="#377EB8"
!$COLOR_INDEX_2="#4DAF4A"
!$COLOR_INDEX_3="#984EA3"
!$COLOR_INDEX_4="#FF7F00"
!$COLOR_INDEX_5="#FFFF33"
!$COLOR_INDEX_6="#A65628"
!$COLOR_INDEX_7="#F781BF"
!$COLOR_INDEX_8="#999999"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#377EB8"
!$COLOR_TEXT_NEUTRAL="#FF7F00"
!$COLOR_TEXT_DARK="#999999"

!$COLOR_REL_COLOR="#999999"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
