
!$COLOR_INDEX_0="#F7F4F9"
!$COLOR_INDEX_1="#E7E1EF"
!$COLOR_INDEX_2="#D4B9DA"
!$COLOR_INDEX_3="#C994C7"
!$COLOR_INDEX_4="#DF65B0"
!$COLOR_INDEX_5="#E7298A"
!$COLOR_INDEX_6="#CE1256"
!$COLOR_INDEX_7="#980043"
!$COLOR_INDEX_8="#67001F"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E7E1EF"
!$COLOR_TEXT_NEUTRAL="#DF65B0"
!$COLOR_TEXT_DARK="#67001F"

!$COLOR_REL_COLOR="#67001F"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
