
!$COLOR_INDEX_0="#FFFFE5"
!$COLOR_INDEX_1="#F7FCB9"
!$COLOR_INDEX_2="#D9F0A3"
!$COLOR_INDEX_3="#ADDD8E"
!$COLOR_INDEX_4="#78C679"
!$COLOR_INDEX_5="#41AB5D"
!$COLOR_INDEX_6="#238443"
!$COLOR_INDEX_7="#006837"
!$COLOR_INDEX_8="#004529"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#F7FCB9"
!$COLOR_TEXT_NEUTRAL="#78C679"
!$COLOR_TEXT_DARK="#004529"

!$COLOR_REL_COLOR="#004529"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
