
!$COLOR_INDEX_0="#FFF5EB"
!$COLOR_INDEX_1="#FEE6CE"
!$COLOR_INDEX_2="#FDD0A2"
!$COLOR_INDEX_3="#FDAE6B"
!$COLOR_INDEX_4="#FD8D3C"
!$COLOR_INDEX_5="#F16913"
!$COLOR_INDEX_6="#D94801"
!$COLOR_INDEX_7="#A63603"
!$COLOR_INDEX_8="#7F2704"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FEE6CE"
!$COLOR_TEXT_NEUTRAL="#FD8D3C"
!$COLOR_TEXT_DARK="#7F2704"

!$COLOR_REL_COLOR="#7F2704"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
