
!$COLOR_INDEX_0="#F7FBFF"
!$COLOR_INDEX_1="#DEEBF7"
!$COLOR_INDEX_2="#C6DBEF"
!$COLOR_INDEX_3="#9ECAE1"
!$COLOR_INDEX_4="#6BAED6"
!$COLOR_INDEX_5="#4292C6"
!$COLOR_INDEX_6="#2171B5"
!$COLOR_INDEX_7="#08519C"
!$COLOR_INDEX_8="#08306B"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#DEEBF7"
!$COLOR_TEXT_NEUTRAL="#6BAED6"
!$COLOR_TEXT_DARK="#08306B"

!$COLOR_REL_COLOR="#08306B"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
