
!$COLOR_INDEX_0="#FFFFE5"
!$COLOR_INDEX_1="#FFF7BC"
!$COLOR_INDEX_2="#FEE391"
!$COLOR_INDEX_3="#FEC44F"
!$COLOR_INDEX_4="#FE9929"
!$COLOR_INDEX_5="#EC7014"
!$COLOR_INDEX_6="#CC4C02"
!$COLOR_INDEX_7="#993404"
!$COLOR_INDEX_8="#662506"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FFF7BC"
!$COLOR_TEXT_NEUTRAL="#FE9929"
!$COLOR_TEXT_DARK="#662506"

!$COLOR_REL_COLOR="#662506"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
