
!$COLOR_INDEX_0="#FFF5F0"
!$COLOR_INDEX_1="#FEE0D2"
!$COLOR_INDEX_2="#FCBBA1"
!$COLOR_INDEX_3="#FC9272"
!$COLOR_INDEX_4="#FB6A4A"
!$COLOR_INDEX_5="#EF3B2C"
!$COLOR_INDEX_6="#CB181D"
!$COLOR_INDEX_7="#A50F15"
!$COLOR_INDEX_8="#67000D"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FEE0D2"
!$COLOR_TEXT_NEUTRAL="#FB6A4A"
!$COLOR_TEXT_DARK="#67000D"

!$COLOR_REL_COLOR="#67000D"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
