
!$COLOR_INDEX_0="#FFF7EC"
!$COLOR_INDEX_1="#FEE8C8"
!$COLOR_INDEX_2="#FDD49E"
!$COLOR_INDEX_3="#FDBB84"
!$COLOR_INDEX_4="#FC8D59"
!$COLOR_INDEX_5="#EF6548"
!$COLOR_INDEX_6="#D7301F"
!$COLOR_INDEX_7="#B30000"
!$COLOR_INDEX_8="#7F0000"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FEE8C8"
!$COLOR_TEXT_NEUTRAL="#FC8D59"
!$COLOR_TEXT_DARK="#7F0000"

!$COLOR_REL_COLOR="#7F0000"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
