
!$COLOR_INDEX_0="#FCFBFD"
!$COLOR_INDEX_1="#EFEDF5"
!$COLOR_INDEX_2="#DADAEB"
!$COLOR_INDEX_3="#BCBDDC"
!$COLOR_INDEX_4="#9E9AC8"
!$COLOR_INDEX_5="#807DBA"
!$COLOR_INDEX_6="#6A51A3"
!$COLOR_INDEX_7="#54278F"
!$COLOR_INDEX_8="#3F007D"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#EFEDF5"
!$COLOR_TEXT_NEUTRAL="#9E9AC8"
!$COLOR_TEXT_DARK="#3F007D"

!$COLOR_REL_COLOR="#3F007D"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
