
!$COLOR_INDEX_0="#FFFFFF"
!$COLOR_INDEX_1="#F0F0F0"
!$COLOR_INDEX_2="#D9D9D9"
!$COLOR_INDEX_3="#BDBDBD"
!$COLOR_INDEX_4="#969696"
!$COLOR_INDEX_5="#737373"
!$COLOR_INDEX_6="#525252"
!$COLOR_INDEX_7="#252525"
!$COLOR_INDEX_8="#000000"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#F0F0F0"
!$COLOR_TEXT_NEUTRAL="#969696"
!$COLOR_TEXT_DARK="#000000"

!$COLOR_REL_COLOR="#000000"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
