
!$COLOR_INDEX_0="#FFF7F3"
!$COLOR_INDEX_1="#FDE0DD"
!$COLOR_INDEX_2="#FCC5C0"
!$COLOR_INDEX_3="#FA9FB5"
!$COLOR_INDEX_4="#F768A1"
!$COLOR_INDEX_5="#DD3497"
!$COLOR_INDEX_6="#AE017E"
!$COLOR_INDEX_7="#7A0177"
!$COLOR_INDEX_8="#49006A"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#FDE0DD"
!$COLOR_TEXT_NEUTRAL="#F768A1"
!$COLOR_TEXT_DARK="#49006A"

!$COLOR_REL_COLOR="#49006A"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
