
!$COLOR_INDEX_0="#F7FCF0"
!$COLOR_INDEX_1="#E0F3DB"
!$COLOR_INDEX_2="#CCEBC5"
!$COLOR_INDEX_3="#A8DDB5"
!$COLOR_INDEX_4="#7BCCC4"
!$COLOR_INDEX_5="#4EB3D3"
!$COLOR_INDEX_6="#2B8CBE"
!$COLOR_INDEX_7="#0868AC"
!$COLOR_INDEX_8="#084081"

!$COLOR_BORDER_COLOR="#000000"

!$COLOR_TEXT_LIGHT="#E0F3DB"
!$COLOR_TEXT_NEUTRAL="#7BCCC4"
!$COLOR_TEXT_DARK="#084081"

!$COLOR_REL_COLOR="#084081"

' Metadata
' Created: 2023-03-22 03:51:00.603881+00:00
