''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' START - Handle local PlantUML render and remote hosting
'
!if (%getenv("LOCAL_EDIT_BLOG_ROOT") == "")
!$THEME_ROOT_PATH = "https://mweagle.io/posts/c4pumlthemes/puml/"
!else
!$THEME_ROOT_PATH = %getenv("LOCAL_EDIT_BLOG_ROOT") + "c4pumlthemes/puml/"
!endif
!define INCLUDE(a,b) ##a##b

' Include the global theme name
!include INCLUDE($THEME_ROOT_PATH, globals.puml)


' Define the theme name we're going to use
!if (%getenv("LOCAL_EDIT_BLOG_ROOT") == "")
!theme $THEME_NAME from https://mweagle.io/posts/c4pumlthemes/puml/resources/palettes
!else
!theme $THEME_NAME from resources/palettes
!endif

!include INCLUDE($THEME_ROOT_PATH, c4-theme-common.puml)
' END - Handle local PlantUML render and remote hosting
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


LAYOUT_WITH_LEGEND()

title System Context diagram for Internet Banking System

Person(customer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")
System(banking_system, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")

System_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")
System_Ext(mainframe, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(customer, banking_system, "Uses")
Rel_Back(customer, mail_system, "Sends e-mails to")
Rel_Neighbor(banking_system, mail_system, "Sends e-mails", "SMTP")
Rel(banking_system, mainframe, "Uses")