@startuml

Title C4 Plant UML Example


!$PALETTE_TYPE = seq
!$PALETTE_NAME = RdPu
!$PALETTE_COLOR_COUNT = 9

!include resources/c4-theme.puml

!include <tupadr3/common>
!include <tupadr3/font-awesome/gitlab>
' Ref: https://github.com/awslabs/aws-icons-for-plantuml
'❗ Syntax of !include <awslib/AWSCommon.puml> uses the embedded
' plantuml-stdlib. As of the PlantUML version 1.2022.14 update,
' this includes the Release 14-2022.07.31 icon set.


!include <awslib/AWSCommon>
!include <awslib/Compute/Lambda>

'!include <awslib/InternetOfThings/IoTRule>
'!include <awslib/Analytics/KinesisDataStreams>
'!include <awslib/ApplicationIntegration/SimpleQueueService>
'
'left to right direction
'
'agent "Published Event" as event #fff
'
'IoTRule(iotRule, "Action Error Rule", "error if Kinesis fails")
'KinesisDataStreams(eventStream, "IoT Events", "2 shards")
'SimpleQueueService(errorQueue, "Rule Error Queue", "failed Rule actions")
'
'event --> iotRule : JSON message
'iotRule --> eventStream : messages
'iotRule --> errorQueue : Failed action message


Person(wat, "NICE", $sprite="gitlab")
Person(customer, "Personal Banking Customer")
System(banking_system, "Internet Banking System")

System_Ext(mail_system, "E-mail system")
System_Ext(mainframe, "Mainframe Banking System")
Container(containerAlias, "Label", "Technology", "Optional Description")
Container_Ext(OthercontainerAlias, "Label", "OTHER Technology", "Optional Description", $sprite="Lambda,scale=0.5")
Component(someComponetn, "THIS THING", "WAT")
Component_Ext(anotherComp, "THIS OTHER THING", "WAT")

Rel(customer, banking_system, "Uses")
Rel_Back(customer, mail_system, "Sends e-mails to")
Rel_Neighbor(banking_system, mail_system, "Sends e-mails")
Rel(banking_system, mainframe, "Uses")

SHOW_LEGEND()

@enduml