@startuml
!$useTheme = "./resources/palettes/puml-theme-cb_seq_Reds_9.puml"
'!$useTheme = "https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes/" +  $useTheme
!include $useTheme
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/percy/TestAllElementsWithLegend.puml
@enduml